chunking:
  chunk_length_minutes: 5
  # max_size_mb: 100

# branding:
#   enabled: true
#   text_format: "Season {season} - Episode {episode} - Part {part}"


# Persian :

branding:
  enabled: true
  text_format: "{season} - قسمت {episode} - پارت {part}"
  logo_path: "input/logo.png"
